### ISSUE TITLE
In C++ it will not work

### ISSUE THREAD

**Issue by lukasz-wiecaszek** [AVnu/gptp#10]
In the file 'common/ieee1588.hpp' default constructor for Timestamp looks as follows:
```
	Timestamp() {
		Timestamp( 0, 0, 0 );
	}
```
This will not work in C++. Could you please correct that in next releases.

By the way, I started to play with this project recently and found some more places, where some improvements/corrections could be applied. Is there a change that I could contribute to this (gptp) project?

**Comment by andrew-elder** [comment]
Could you please elaborate? You are the first person to report this issue.... Are you getting an error with a specific toolchain?

If you wish to contribute a change, just make a pull request. Thank you for your interest.

**Comment by lukasz-wiecaszek** [comment]
I am sorry. I thought that it is so obvious. In C++ the construct 
```
	Timestamp() {
		Timestamp( 0, 0, 0 );
	}
```
just creates a local/temporary Timestamp (0,0,0) object on stack, and leaving Timestamp() default constructor this local object will be destroyed. The overall Timestamp object will be created with uninitialized values for nanoseconds, seconds_ls, seconds_ms and _version.
This bug is not related to any toolchain.  I am using Gentoo distro but as said this is not toolchain related. This is common mistake for people switching for example from Java to C++.

**Comment by andrew-elder** [comment]
Thanks for the clarification! I would be pleased to accept a pull request that fixes this.

**Comment by andrew-elder** [comment]
PR has been merged. I think we can close this one?

**Comment by lukasz-wiecaszek** [comment]
Of course issue can be closed now. Thanks for your support.
