### ISSUE TITLE
No threads sync during shutdown results in segmentation fault

### ISSUE THREAD

**Issue by PawelModrzejewski** [AVnu/gptp#19]
Currently there is no threads synchronization during daemon shutdown. On Linux two sources of segmentation fault were identified (for slave only) so far:
* _**ipc**_ - deleted at the end of main thread and accessed while processing FollowUp message (in IEEE1588Clock::setMasterOffset function, _ipc->update()_);
* _**ether_phy_delay**_ - created/destroyed in the main thread and still accessed while trying to process messages (in CommonPort::getRxPhyDelay, could be also in CommonPort::getTxPhyDelay, _phy_delay->count()_)

It is quite sporadic (1/X00) and it has been fixed (and well tested in slave mode) on our side by adding/calling pthread_cancel() and _join() for "watchNetLink" and "openPort" threads at the end of main thread. Those threads should be "cancelled" at POSIX.1 cancellation points, which are _recv()_ and _select()_ functions in those cases.

Is there someone interested in pull request with mentioned changes or do you see other (better) ways to fix it? Any comments appreciated.

**Comment by andrew-elder** [comment]
This sounds like excellent work. I would submit the pull request and let the discussion and review continue alongside the PR. Thanks for this!

**Comment by andrew-elder** [comment]
@PawelModrzejewski - this has been fixed right? Do you want to close the issue?

**Comment by PawelModrzejewski** [comment]
Yes, we can close it, thanks for reminder.
