### ISSUE TITLE
gptp release

### ISSUE THREAD

**Issue by sugnanprabhu** [AVnu/gptp#4]
Now that the gptp is separated out of the OpenAvnu code, can we have a separate release for the gptp starting with the versioning v1.0

**Comment by andrew-elder** [comment]
Sure. I assume we/you would create release notes as well? I'm open to a pull request with a release tag and some sort of history document. Please add other comments.

**Comment by sugnanprabhu** [comment]
@andrew-elder I can create the required notes and history document. Let me know, if you want me to follow some reference format. But for release tag as per my knowledge, we cannot raise a PR for tags.

**Comment by sugnanprabhu** [comment]
[Release notes.txt](https://github.com/AVnu/gptp/files/2459412/Release.notes.txt)

@andrew-elder Let me know if the attached release notes looks ok to you.

**Comment by sugnanprabhu** [comment]
[history.txt](https://github.com/AVnu/gptp/files/2459801/history.txt)

I have generated a history of the PR's for gptp from earlier project.
This can be included in the release notes or as separate history document.

**Comment by andrew-elder** [comment]
Thanks. Should the file types be .md instead of .txt? They are markdown formatted, right?

Also, are you planning to put a version number in the Release notes.txt file?

**Comment by sugnanprabhu** [comment]
@andrew-elder 
Forgot to mention, yes it should be .md but github does not support attaching .md files in the comment, hence had renamed to .txt

For version can we start with v1.0? I have added the same in the attachment.
[Release notes.txt](https://github.com/AVnu/gptp/files/2461226/Release.notes.txt)

**Comment by sugnanprabhu** [comment]
@andrew-elder Can you please make a first official release? Let me know if you need any other details.

**Comment by andrew-elder** [comment]
Please do a pull request with history.md and release_notes.md in them. That way we can tag the notes files as well.

**Comment by sugnanprabhu** [comment]
@andrew-elder Now that the documents are merged, can you please make the first official release?

**Comment by andrew-elder** [comment]
Done. I tagged v1.0.0.
