### ISSUE TITLE
Static code analysis _036 (Null Pointer Dereference)

### ISSUE THREAD

**Issue by PawelModrzejewski** [Avnu/gptp#63]
Short summary (details in attached file):

    LinuxGPTPPersistFile::triggerWriteStorage()
    .../linux/src/linux_hal_persist_file.cpp
    
        bool triggerWriteStorage(void)
        {
                if (!writeCB) {
                	
    event Event 2:  Considering the case where writeCB must have been equal to 0.
                        GPTP_LOG_ERROR("Persistent write callback not registered");
                }
                bool result = false;
                if (memoryDataLength > storedDataLength) {
                ...
                }
                writeCB((char *)restoredata, storedDataLength);
                	
    Null Pointer Dereference: writeCB is dereferenced here, but it is NULL.

[gptp_036.txt](https://github.com/Avnu/gptp/files/5709714/gptp_036.txt)

**Comment by MarcinMiklas** [comment]
Fix was merged.
