### ISSUE TITLE
Static code analysis _029 (No Space For Null Terminator)

### ISSUE THREAD

**Issue by PawelModrzejewski** [Avnu/gptp#64]
Short summary (details in attached file):

    InterfaceName::InterfaceName()
    .../common/avbts_osnet.hpp
    
	InterfaceName(char *name, int length) {
		this->name = new char[length + 1];
		PLAT_strncpy(this->name, name, length);
	}
    strncpy() may write a non-null value into the very last byte of the string.
    The string's capacity is length + 1, which is bounded above by 1073741824 and the length of the string pointed to by name and below by 1. The last character written by strncpy() could be character length + 1 - 1, which evaluates to length, which is bounded above by 1073741823 and the length of the string pointed to by name, minus 1 and below by 0.
    If a subsequent statement definitely null-terminates the string, you can safely ignore this warning.

[gptp_029.txt](https://github.com/Avnu/gptp/files/5710762/gptp_029.txt)

**Comment by MarcinMiklas** [comment]
Fix was merged.
