### ISSUE TITLE
Static code analysis _037 (Coercion Alters Value - phdly)

### ISSUE THREAD

**Issue by PawelModrzejewski** [Avnu/gptp#68]
Short summary (details in attached file):

    GptpIniParser::iniCallBack()
    .../common/gptp_cfg.cpp
                parser->_config.phy_delay[LINKSPEED_1G].set_tx_delay( phdly );
    
    phdly is coerced from int to unsigned short.
    phdly evaluates to strtoul(value, &pEnd, 10)gptp_cfg.cpp:158.
    Coercing them to unsigned short can cause data loss or sign change.

[gptp_037.txt](https://github.com/Avnu/gptp/files/5729229/gptp_037.txt)

**Comment by MarcinMiklas** [comment]
Fix was merged
