### ISSUE TITLE
Pdelay_Req messages: logMeanMessageInterval not set accordingly 

### ISSUE THREAD

**Issue by Tassenpudding** [Avnu/gptp#79]
As this is a gPTP client i assume the underlying specification is IEEE802.1AS.
According to IEEE802.AS 11.4.2.8
"For Pdelay_Req messages, the value is the value of currentLogPdelayReqInterval."
So in common/ptp_messages.cpp line 1253
```logMeanMessageInterval = 0;```
should be
```logMeanMessageInterval = port->getPDelayInterval();```
Is my assumption correct?
I will add a pull request if possible

**Comment by MarcinMiklas** [comment]
Fix was merged
