### ISSUE TITLE
Unable to assign current timestamp and sequenceID during live capturing.

### ISSUE THREAD

**Issue by swamyb3679** [AVnu/gptp#8]
**Brief description:**

Using pyshark, we are able to capture the live logs. But here, current timestamp and sequenceID parameter values are getting assigned inappropriately from server side to the client side, due to the delay of live capturing.

Server side, we are running gptp daemon_cl.
Client side, we are pumping the dummy packets.

**Environment:**

Scapy version: 2.4.0
Python version: 3.6.6
Operating System: Ubuntu18.04

**Expected Result:**

Server side timestamp and sequenceID **should match** with the Client side timestamp and sequenceID parameters

**Comment by pinealservo** [comment]
I'm sorry, I don't quite understand what you are expecting and which timestamps you are referring to. It might help to include a packet capture along with a detailed description of how it is different from what you expected. Please also let us know what NICs you are using on your gPTP endpoints and what switches, if any, are between them. It might also help to give some context as to why you are trying to capture these logs and what you are hoping to learn or verify with them.
