### ISSUE TITLE
how to use gptp?

### ISSUE THREAD

**Issue by wasdzy111** [Avnu/gptp#86]
hi,Start gptp in linux：master：./gptp eno1 -T ，slave：./gptp eno1 -L

Need to modify the value of GPTP_MULTICAST？

I always report errors in the same network（PDelay Response Receipt Timeout），Please help me！thanks！

**Comment by wasdzy111** [comment]
It turned out that my LAN blocked multicas

**Comment by Sulovegxh** [comment]
大哥，这个应该怎么使用啊？

**Comment by Sulovegxh** [comment]
加一下QQ啊，562770150
