### ISSUE TITLE
Calculation of GTI

### ISSUE THREAD

**Issue by Debarun-RC** [Avnu/gptp#88]
Hi,

  I am studying the gPTP daemon source code. I have a query regarding the GTI value calculation. Below is the section

static int ravb_set_gti(struct net_device *ndev)
{
        struct ravb_private *priv = netdev_priv(ndev);
        struct device *dev = ndev->dev.parent;
        unsigned long rate;
        uint64_t inc;

        rate = clk_get_rate(priv->clk);
        if (!rate)
                return -EINVAL;

        inc = 1000000000ULL << 20;
        do_div(inc, rate);

        if (inc < GTI_TIV_MIN || inc > GTI_TIV_MAX) {
                dev_err(dev, "gti.tiv increment 0x%llx is outside the range 0x%x - 0x%x\n",
                        inc, GTI_TIV_MIN, GTI_TIV_MAX);
                return -EINVAL;
        }

        ravb_write(ndev, inc, GTI);

        return 0;
}

It would be very helpful, if the calculation of "inc" can be explained a bit (e.g, why is it initialized to  inc = 1000000000ULL << 20)

Any feedback will be highly appreciated.

Thanking in advance.

Best Regards,
Debarun

**Comment by PawelModrzejewski** [comment]
Well, I don't think it's a part of AVnu/gptp code ;-)

**Comment by MarcinMiklas** [comment]
I agree with Pawel, this code snipped is nowhere to be found in AVnu/gptp.
